"""added resets table

Revision ID: 3fe0cd816cfe
Revises: 4595c5f4c9a8
Create Date: 2024-11-17 15:35:39.465582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fe0cd816cfe'
down_revision: Union[str, None] = '4595c5f4c9a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('date_of_creation', sa.String(), nullable=False),
    sa.Column('expiration_date', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resets')
    # ### end Alembic commands ###
